### ISSUE TITLE
The plugin `crossview` doesn't have a main class

### ISSUE THREAD

**Issue by xiaocode** [warioddly/crossview#1]
When add this package to flutter:

The plugin `crossview` doesn't have a main class defined in
/home/***/.pub-cache/hosted/pub.flutter-io.cn/crossview-0.0.4/android/src/main/java/com/warioddly/crossview/CrossViewPlugin.java or
/home/***/.pub-cache/hosted/pub.flutter-io.cn/crossview-0.0.4/android/src/main/kotlin/com/warioddly/crossview/CrossViewPlugin.kt. This is likely to due to an
incorrect `androidPackage: com.warioddly.crossview` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of
this plugin and consider using a different plugin in the meanwhile.

**Comment by warioddly** [comment]
Hey! 
For issues like "The plugin **`crossview`** doesn't have a main class defined in..."

Steps:
- Delete pubspec.lock
- Delete C:\Users\{USERNAME}\AppData\Local\Pub\Cache\hosted\pub.dev.cache folder
- Delete packages liked with plugin '**`crossview`**' under above directory
- Run '**`flutter clean`**'
- Run '**`flutter pub get`**'

Done!
